#!/bin/sh

BLANK='#cba6f7d8'
CLEAR='#ffffff22'
DEFAULT='#1e1e2ed8'
TEXT='#ffffffff'
WRONG='#f38ba8bb'
VERIFYING='#a6e3a1e6'

i3lock \
  --insidever-color=$CLEAR \
  --ringver-color=$VERIFYING \
  \
  --insidewrong-color=$CLEAR \
  --ringwrong-color=$WRONG \
  \
  --inside-color=$BLANK \
  --ring-color=$DEFAULT \
  --line-color=$BLANK \
  --separator-color=$DEFAULT \
  \
  --verif-color=$TEXT \
  --wrong-color=$TEXT \
  --time-color=$TEXT \
  --date-color=$TEXT \
  --layout-color=$TEXT \
  --keyhl-color=$WRONG \
  --bshl-color=$WRONG \
  \
  --screen 1 \
  --blur 9 \
  --clock \
  --indicator \
  --time-str="%H:%M:%S" \
  --date-str="%d/%m/%Y"
